/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ButtonConfig {
  'link' : string,
  'enabled' : boolean,
  'buttonLabel' : string,
}
export interface CateringEvent {
  'organizer' : string,
  'date' : string,
  'email' : string,
  'timestamp' : Time,
  'details' : string,
  'guests' : bigint,
  'eventName' : string,
}
export interface Contact {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface ExportData {
  'promotions' : Array<Promotion>,
  'openingHours' : Array<OpeningHour>,
  'whatsappConfig' : ButtonConfig,
  'pages' : Array<Page>,
  'location' : Location,
  'callConfig' : ButtonConfig,
  'orderConfig' : ButtonConfig,
}
export interface Location {
  'email' : string,
  'address' : string,
  'phone' : string,
  'coordinates' : string,
}
export interface MetaData {
  'title' : string,
  'description' : string,
  'keywords' : string,
}
export interface OpeningHour {
  'day' : string,
  'close' : string,
  'open' : string,
}
export interface Page {
  'title' : string,
  'content' : string,
  'meta' : MetaData,
  'slug' : string,
}
export interface Promotion {
  'end' : [] | [Time],
  'title' : string,
  'active' : boolean,
  'order' : bigint,
  'link' : [] | [string],
  'description' : string,
  'start' : [] | [Time],
  'imageUrl' : string,
}
export interface Reservation {
  'date' : string,
  'name' : string,
  'specialRequests' : [] | [string],
  'email' : string,
  'timestamp' : Time,
  'guests' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOpeningHour' : ActorMethod<[string, string, string], undefined>,
  'addPromotion' : ActorMethod<
    [string, string, string, [] | [string], [] | [Time], [] | [Time], bigint],
    Principal
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPage' : ActorMethod<[string, string, string, MetaData], undefined>,
  'deletePage' : ActorMethod<[string], undefined>,
  'deletePromotion' : ActorMethod<[Principal], undefined>,
  'exportData' : ActorMethod<[], ExportData>,
  'getActivePromotions' : ActorMethod<[], Array<Promotion>>,
  'getAllCateringEvents' : ActorMethod<[], Array<CateringEvent>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllPages' : ActorMethod<[], Array<Page>>,
  'getAllPromotions' : ActorMethod<[], Array<Promotion>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getCallConfig' : ActorMethod<[], ButtonConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLocation' : ActorMethod<[], Location>,
  'getOpeningHours' : ActorMethod<[], Array<OpeningHour>>,
  'getOrderConfig' : ActorMethod<[], ButtonConfig>,
  'getPage' : ActorMethod<[string], [] | [Page]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWhatsappConfig' : ActorMethod<[], ButtonConfig>,
  'importData' : ActorMethod<[ExportData], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeOpeningHour' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCateringEvent' : ActorMethod<
    [string, string, string, string, bigint, string],
    undefined
  >,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
  'submitReservation' : ActorMethod<
    [string, string, string, bigint, [] | [string]],
    undefined
  >,
  'updateCallConfig' : ActorMethod<[ButtonConfig], undefined>,
  'updateLocation' : ActorMethod<[Location], undefined>,
  'updateOrderConfig' : ActorMethod<[ButtonConfig], undefined>,
  'updatePage' : ActorMethod<[string, string, string, MetaData], undefined>,
  'updatePromotion' : ActorMethod<
    [
      Principal,
      string,
      string,
      string,
      [] | [string],
      [] | [Time],
      [] | [Time],
      boolean,
      bigint,
    ],
    undefined
  >,
  'updateWhatsappConfig' : ActorMethod<[ButtonConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];