/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MetaData = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'keywords' : IDL.Text,
});
export const Promotion = IDL.Record({
  'end' : IDL.Opt(Time),
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'order' : IDL.Nat,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'start' : IDL.Opt(Time),
  'imageUrl' : IDL.Text,
});
export const OpeningHour = IDL.Record({
  'day' : IDL.Text,
  'close' : IDL.Text,
  'open' : IDL.Text,
});
export const ButtonConfig = IDL.Record({
  'link' : IDL.Text,
  'enabled' : IDL.Bool,
  'buttonLabel' : IDL.Text,
});
export const Page = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'meta' : MetaData,
  'slug' : IDL.Text,
});
export const Location = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'coordinates' : IDL.Text,
});
export const ExportData = IDL.Record({
  'promotions' : IDL.Vec(Promotion),
  'openingHours' : IDL.Vec(OpeningHour),
  'whatsappConfig' : ButtonConfig,
  'pages' : IDL.Vec(Page),
  'location' : Location,
  'callConfig' : ButtonConfig,
  'orderConfig' : ButtonConfig,
});
export const CateringEvent = IDL.Record({
  'organizer' : IDL.Text,
  'date' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
  'guests' : IDL.Nat,
  'eventName' : IDL.Text,
});
export const Contact = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Reservation = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'timestamp' : Time,
  'guests' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOpeningHour' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPromotion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Nat,
      ],
      [IDL.Principal],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, MetaData], [], []),
  'deletePage' : IDL.Func([IDL.Text], [], []),
  'deletePromotion' : IDL.Func([IDL.Principal], [], []),
  'exportData' : IDL.Func([], [ExportData], ['query']),
  'getActivePromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getAllCateringEvents' : IDL.Func([], [IDL.Vec(CateringEvent)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
  'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getCallConfig' : IDL.Func([], [ButtonConfig], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLocation' : IDL.Func([], [Location], ['query']),
  'getOpeningHours' : IDL.Func([], [IDL.Vec(OpeningHour)], ['query']),
  'getOrderConfig' : IDL.Func([], [ButtonConfig], ['query']),
  'getPage' : IDL.Func([IDL.Text], [IDL.Opt(Page)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWhatsappConfig' : IDL.Func([], [ButtonConfig], ['query']),
  'importData' : IDL.Func([ExportData], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeOpeningHour' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCateringEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateCallConfig' : IDL.Func([ButtonConfig], [], []),
  'updateLocation' : IDL.Func([Location], [], []),
  'updateOrderConfig' : IDL.Func([ButtonConfig], [], []),
  'updatePage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, MetaData], [], []),
  'updatePromotion' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Bool,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateWhatsappConfig' : IDL.Func([ButtonConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MetaData = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'keywords' : IDL.Text,
  });
  const Promotion = IDL.Record({
    'end' : IDL.Opt(Time),
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'order' : IDL.Nat,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'start' : IDL.Opt(Time),
    'imageUrl' : IDL.Text,
  });
  const OpeningHour = IDL.Record({
    'day' : IDL.Text,
    'close' : IDL.Text,
    'open' : IDL.Text,
  });
  const ButtonConfig = IDL.Record({
    'link' : IDL.Text,
    'enabled' : IDL.Bool,
    'buttonLabel' : IDL.Text,
  });
  const Page = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'meta' : MetaData,
    'slug' : IDL.Text,
  });
  const Location = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'coordinates' : IDL.Text,
  });
  const ExportData = IDL.Record({
    'promotions' : IDL.Vec(Promotion),
    'openingHours' : IDL.Vec(OpeningHour),
    'whatsappConfig' : ButtonConfig,
    'pages' : IDL.Vec(Page),
    'location' : Location,
    'callConfig' : ButtonConfig,
    'orderConfig' : ButtonConfig,
  });
  const CateringEvent = IDL.Record({
    'organizer' : IDL.Text,
    'date' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
    'guests' : IDL.Nat,
    'eventName' : IDL.Text,
  });
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Reservation = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'timestamp' : Time,
    'guests' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOpeningHour' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPromotion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Nat,
        ],
        [IDL.Principal],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, MetaData], [], []),
    'deletePage' : IDL.Func([IDL.Text], [], []),
    'deletePromotion' : IDL.Func([IDL.Principal], [], []),
    'exportData' : IDL.Func([], [ExportData], ['query']),
    'getActivePromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getAllCateringEvents' : IDL.Func([], [IDL.Vec(CateringEvent)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
    'getAllPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getCallConfig' : IDL.Func([], [ButtonConfig], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLocation' : IDL.Func([], [Location], ['query']),
    'getOpeningHours' : IDL.Func([], [IDL.Vec(OpeningHour)], ['query']),
    'getOrderConfig' : IDL.Func([], [ButtonConfig], ['query']),
    'getPage' : IDL.Func([IDL.Text], [IDL.Opt(Page)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhatsappConfig' : IDL.Func([], [ButtonConfig], ['query']),
    'importData' : IDL.Func([ExportData], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeOpeningHour' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCateringEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateCallConfig' : IDL.Func([ButtonConfig], [], []),
    'updateLocation' : IDL.Func([Location], [], []),
    'updateOrderConfig' : IDL.Func([ButtonConfig], [], []),
    'updatePage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, MetaData], [], []),
    'updatePromotion' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Bool,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateWhatsappConfig' : IDL.Func([ButtonConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };