/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    email: string;
    address: string;
    phone: string;
    coordinates: string;
}
export interface Promotion {
    end?: Time;
    title: string;
    active: boolean;
    order: bigint;
    link?: string;
    description: string;
    start?: Time;
    imageUrl: string;
}
export interface ExportData {
    promotions: Array<Promotion>;
    openingHours: Array<OpeningHour>;
    whatsappConfig: ButtonConfig;
    pages: Array<Page>;
    location: Location;
    callConfig: ButtonConfig;
    orderConfig: ButtonConfig;
}
export type Time = bigint;
export interface Page {
    title: string;
    content: string;
    meta: MetaData;
    slug: string;
}
export interface Contact {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface ButtonConfig {
    link: string;
    enabled: boolean;
    buttonLabel: string;
}
export interface Reservation {
    date: string;
    name: string;
    specialRequests?: string;
    email: string;
    timestamp: Time;
    guests: bigint;
}
export interface CateringEvent {
    organizer: string;
    date: string;
    email: string;
    timestamp: Time;
    details: string;
    guests: bigint;
    eventName: string;
}
export interface MetaData {
    title: string;
    description: string;
    keywords: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface OpeningHour {
    day: string;
    close: string;
    open: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOpeningHour(day: string, open: string, close: string): Promise<void>;
    addPromotion(title: string, description: string, imageUrl: string, link: string | null, start: Time | null, end: Time | null, order: bigint): Promise<Principal>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPage(title: string, content: string, slug: string, meta: MetaData): Promise<void>;
    deletePage(slug: string): Promise<void>;
    deletePromotion(id: Principal): Promise<void>;
    exportData(): Promise<ExportData>;
    getActivePromotions(): Promise<Array<Promotion>>;
    getAllCateringEvents(): Promise<Array<CateringEvent>>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllPages(): Promise<Array<Page>>;
    getAllPromotions(): Promise<Array<Promotion>>;
    getAllReservations(): Promise<Array<Reservation>>;
    getCallConfig(): Promise<ButtonConfig>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLocation(): Promise<Location>;
    getOpeningHours(): Promise<Array<OpeningHour>>;
    getOrderConfig(): Promise<ButtonConfig>;
    getPage(slug: string): Promise<Page | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWhatsappConfig(): Promise<ButtonConfig>;
    importData(data: ExportData): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeOpeningHour(day: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitCateringEvent(eventName: string, organizer: string, email: string, date: string, guests: bigint, details: string): Promise<void>;
    submitContact(name: string, email: string, message: string): Promise<void>;
    submitReservation(name: string, email: string, date: string, guests: bigint, specialRequests: string | null): Promise<void>;
    updateCallConfig(config: ButtonConfig): Promise<void>;
    updateLocation(newLocation: Location): Promise<void>;
    updateOrderConfig(config: ButtonConfig): Promise<void>;
    updatePage(slug: string, title: string, content: string, meta: MetaData): Promise<void>;
    updatePromotion(id: Principal, title: string, description: string, imageUrl: string, link: string | null, start: Time | null, end: Time | null, active: boolean, order: bigint): Promise<void>;
    updateWhatsappConfig(config: ButtonConfig): Promise<void>;
}
import type { ButtonConfig as _ButtonConfig, ExportData as _ExportData, Location as _Location, OpeningHour as _OpeningHour, Page as _Page, Promotion as _Promotion, Reservation as _Reservation, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOpeningHour(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOpeningHour(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOpeningHour(arg0, arg1, arg2);
            return result;
        }
    }
    async addPromotion(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: Time | null, arg5: Time | null, arg6: bigint): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.addPromotion(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPromotion(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPage(arg0: string, arg1: string, arg2: string, arg3: MetaData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deletePage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePage(arg0);
            return result;
        }
    }
    async deletePromotion(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePromotion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePromotion(arg0);
            return result;
        }
    }
    async exportData(): Promise<ExportData> {
        if (this.processError) {
            try {
                const result = await this.actor.exportData();
                return from_candid_ExportData_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportData();
            return from_candid_ExportData_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivePromotions(): Promise<Array<Promotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivePromotions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePromotions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCateringEvents(): Promise<Array<CateringEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCateringEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCateringEvents();
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getAllPages(): Promise<Array<Page>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPages();
            return result;
        }
    }
    async getAllPromotions(): Promise<Array<Promotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPromotions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPromotions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReservations();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReservations();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallConfig(): Promise<ButtonConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallConfig();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(): Promise<Location> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation();
            return result;
        }
    }
    async getOpeningHours(): Promise<Array<OpeningHour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpeningHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpeningHours();
            return result;
        }
    }
    async getOrderConfig(): Promise<ButtonConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderConfig();
            return result;
        }
    }
    async getPage(arg0: string): Promise<Page | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPage(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPage(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhatsappConfig(): Promise<ButtonConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhatsappConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhatsappConfig();
            return result;
        }
    }
    async importData(arg0: ExportData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(to_candid_ExportData_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(to_candid_ExportData_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeOpeningHour(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeOpeningHour(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeOpeningHour(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitCateringEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCateringEvent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCateringEvent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2);
            return result;
        }
    }
    async submitReservation(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReservation(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReservation(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateCallConfig(arg0: ButtonConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallConfig(arg0);
            return result;
        }
    }
    async updateLocation(arg0: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0);
            return result;
        }
    }
    async updateOrderConfig(arg0: ButtonConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderConfig(arg0);
            return result;
        }
    }
    async updatePage(arg0: string, arg1: string, arg2: string, arg3: MetaData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updatePromotion(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: Time | null, arg6: Time | null, arg7: boolean, arg8: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePromotion(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePromotion(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async updateWhatsappConfig(arg0: ButtonConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWhatsappConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWhatsappConfig(arg0);
            return result;
        }
    }
}
function from_candid_ExportData_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportData): ExportData {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Promotion_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Promotion): Promotion {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Reservation_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reservation): Reservation {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Page]): Page | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    name: string;
    specialRequests: [] | [string];
    email: string;
    timestamp: _Time;
    guests: bigint;
}): {
    date: string;
    name: string;
    specialRequests?: string;
    email: string;
    timestamp: Time;
    guests: bigint;
} {
    return {
        date: value.date,
        name: value.name,
        specialRequests: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.specialRequests)),
        email: value.email,
        timestamp: value.timestamp,
        guests: value.guests
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    promotions: Array<_Promotion>;
    openingHours: Array<_OpeningHour>;
    whatsappConfig: _ButtonConfig;
    pages: Array<_Page>;
    location: _Location;
    callConfig: _ButtonConfig;
    orderConfig: _ButtonConfig;
}): {
    promotions: Array<Promotion>;
    openingHours: Array<OpeningHour>;
    whatsappConfig: ButtonConfig;
    pages: Array<Page>;
    location: Location;
    callConfig: ButtonConfig;
    orderConfig: ButtonConfig;
} {
    return {
        promotions: from_candid_vec_n7(_uploadFile, _downloadFile, value.promotions),
        openingHours: value.openingHours,
        whatsappConfig: value.whatsappConfig,
        pages: value.pages,
        location: value.location,
        callConfig: value.callConfig,
        orderConfig: value.orderConfig
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    end: [] | [_Time];
    title: string;
    active: boolean;
    order: bigint;
    link: [] | [string];
    description: string;
    start: [] | [_Time];
    imageUrl: string;
}): {
    end?: Time;
    title: string;
    active: boolean;
    order: bigint;
    link?: string;
    description: string;
    start?: Time;
    imageUrl: string;
} {
    return {
        end: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.end)),
        title: value.title,
        active: value.active,
        order: value.order,
        link: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.link)),
        description: value.description,
        start: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.start)),
        imageUrl: value.imageUrl
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reservation>): Array<Reservation> {
    return value.map((x)=>from_candid_Reservation_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Promotion>): Array<Promotion> {
    return value.map((x)=>from_candid_Promotion_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ExportData_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExportData): _ExportData {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Promotion_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Promotion): _Promotion {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    promotions: Array<Promotion>;
    openingHours: Array<OpeningHour>;
    whatsappConfig: ButtonConfig;
    pages: Array<Page>;
    location: Location;
    callConfig: ButtonConfig;
    orderConfig: ButtonConfig;
}): {
    promotions: Array<_Promotion>;
    openingHours: Array<_OpeningHour>;
    whatsappConfig: _ButtonConfig;
    pages: Array<_Page>;
    location: _Location;
    callConfig: _ButtonConfig;
    orderConfig: _ButtonConfig;
} {
    return {
        promotions: to_candid_vec_n21(_uploadFile, _downloadFile, value.promotions),
        openingHours: value.openingHours,
        whatsappConfig: value.whatsappConfig,
        pages: value.pages,
        location: value.location,
        callConfig: value.callConfig,
        orderConfig: value.orderConfig
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    end?: Time;
    title: string;
    active: boolean;
    order: bigint;
    link?: string;
    description: string;
    start?: Time;
    imageUrl: string;
}): {
    end: [] | [_Time];
    title: string;
    active: boolean;
    order: bigint;
    link: [] | [string];
    description: string;
    start: [] | [_Time];
    imageUrl: string;
} {
    return {
        end: value.end ? candid_some(value.end) : candid_none(),
        title: value.title,
        active: value.active,
        order: value.order,
        link: value.link ? candid_some(value.link) : candid_none(),
        description: value.description,
        start: value.start ? candid_some(value.start) : candid_none(),
        imageUrl: value.imageUrl
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Promotion>): Array<_Promotion> {
    return value.map((x)=>to_candid_Promotion_n22(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
